# Use `docker compose up --force-recreate --build web` to run the container

services:
  web:
    build: .
    ports:
      - "8000:8000"
    # volumes:
    #   - /dev/mnt/data/books:/app/books:ro
    restart: unless-stopped